### ISSUE TITLE
Total failure

### ISSUE THREAD

**Issue by CBodwyn** [jdogresorg/FreeWallet#11]
Cant get my btc to send from either of 2 addresses.  2 diff errors..  How do we proceed for you to send it out and close my acct please?  Thanks.  Charley.

**Comment by jdogresorg** [comment]
This is not a technical support forum. This is a forum for reporting DETAILED issues with the app... If you have an issue, you need to give details which can be used to lookup information about your addresses. If you get an "error", you should post the error message here so that there is some indicator of what is going wrong.

At this point your basically just saying stuff is broken, but give no details which can be used to verify if anything is broken, and if so, what.

FreeWallet is an open-source application, and as the developer I have no access to any "accounts". 

When you first started using FreeWallet you were prompted to write down a 12-word passphrase. That 12-word passphrase is how you access your "account". 

If your having issues with freewallet, you might want to try logging in at counterwallet.io using that same 12-word passphrase from freewallet. This will allow you to view any addresses "accounts" and any funds (BTC, XCP, or assets) for those addresses.

**Comment by CBodwyn** [comment]
Trying counterwallet. And im not an idiot but thought there might be a less public way to communicate details.  Thus why i asked how to proceed.  And this was stated to be the only way to address wallet issues, technical support or otherwise.  I was vague for a reason and dont believe condescension was warranted.  Ill be more publicly detailed in the future if you'll not be so assumptive of our level of stupidity.  Thanks.  Charley.

**Comment by jdogresorg** [comment]
Sorry you feel I was condescending. My intent was simply to make it clear that :

1.) If you have a technical issue, post the technical details of the issue so that I can investigate the issue

2.) I don't offer support for non-technical issues (like "refund my money" or "close my account")

Please feel free to post another issue if you discover a technical issue which you can document and repeat. 

FYI, There is currently an issue with the chain.so API where at times it will fail to broadcast a signed transaction. I will be fixing this issue in the next release which should be out in a few weeks :)
