### ISSUE TITLE
Unable to set low fees

### ISSUE THREAD

**Issue by ajayyy** [jdogresorg/freewallet#14]
Even when I set my fee to something like 0.0001 or even lower I get the following error message when trying to transfer funds

> Error composing send transaction via API: Insufficient BTC at address 1ENvDB4XNecBsQrqvN1rfjFjm1ssLjbqLD. (Need approximately 0.00260933 BTC.) To spend unconfirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi‐sig addresses.)

**Comment by jdogresorg** [comment]
This is not a technical issue with Freewallet. The message is coming directly from Counterparty and is well documented over on counterpartytalk.org.

Simple solution is to send some funds to your address (0.01 BTC or so) and the message will go away... You can get more info by searching at :
https://counterpartytalk.org/search?q=Insufficient%20BTC

**Comment by ajayyy** [comment]
Ok thanks, I was not getting this message from the normal counterwallet site so I posted the issue here.

**Comment by jdogresorg** [comment]
No worries... appreciate the heads up on technical issues :)

Perhaps earlier you weren't getting the message in counterwallet because at that time you had funds to cover the tx fees. In any case, all FreeWallet does is take your exact fee preferences and pass it on to CP to generate the transaction...the exact same thing that counterwallet does, so I don't think this is a freewallet specific issue.
