### ISSUE TITLE
Transaction priority dropdown not working

### ISSUE THREAD

**Issue by informatorius** [jdogresorg/freewallet#7]
I tried Freewallet Desktop Windows v0.9.5 and transaction priority change from High, Medium, Low does not change the fee shown to the left. (Workaround: Custom fee shows 0 and I can enter what I want. )

**Comment by jdogresorg** [comment]
I believe the issue is that the low and high fee estimates from blocktrail's APIs are the same amount.

The fees information is taken directly from the blocktrail.com API. Occasionally the high and low fee will be the same amount due to the way that blocktrail calculates the "optimum" and "low" fees.

Currently Blocktrail uses the following logic for "Low" and "High" fee calculations :
High = 75% chance of getting into next block
Low  = 75% chance of getting into a block within the next 2 blocks

Typically this logic works fine and results in fast transactions, but when the blockchain is under heavy load, the high and low fee estimates from blocktrail can indicate the same exact fee.

If this is an issue that I continue to hear is happening, I will probably wind up replacing the blocktrail API calls with fee estimates data from https://bitcoinfees.21.co

I will leave this issue open for a few months to let others comment as well and see how prevalent the problem is.

**Comment by jdogresorg** [comment]
we now take our fee calcuations from https://bitcoinfees.earn.com/api and no longer use blocktrail
