### ISSUE TITLE
coinmarketcap cors issue

### ISSUE THREAD

**Issue by sull** [jdogresorg/FreeWallet#8]
> XMLHttpRequest cannot load https://api.coinmarketcap.com/v1/ticker/?_dc=1493933013556. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://freewallet.io' is therefore not allowed access.

I added a proxy to call this API server-side and avoid this error now. Thought it might solve my inability to send from freewallet but still unable to. 

Maybe contact CMC to see about their CORS same-origin policy.

**Comment by sull** [comment]
Tried countertools wallet to test since i think similar APIs used. here is console screenshot. if I have real time to look into it, i'll follow up.

<img width="1329" alt="screen shot 2017-05-06 at 9 35 03 am" src="https://cloud.githubusercontent.com/assets/6834/25772867/cf6a2b16-3241-11e7-9c33-f53f42ae64ab.png">

**Comment by jdogresorg** [comment]
I believe there are 2 issues going on

1.) Coinmarketcap is using a new API and depreciated the old one (CORS issue)
2.) Issue Broadcasting signed transaction via chain.so

The issue is coinmarketcap changed their API without notifying anyone.
The new API is at : https://api.coinmarketcap.com/v1/ticker/bitcoin/
I have fixed the issue on counterpartychain.io to use the new API... just need to update freewallet now

The issue with broadcasting a signed tx will need to be fixed... I might just setup an API on xchain.io to allow pushing signed transactions.

Thanks for reporting these issues, they will get fixed shortly (within next few weeks)

**Comment by sull** [comment]
no prob. yeah I mixed two issues here. should have added separate issue.

**Comment by jdogresorg** [comment]
closed with c76a21984abc3282781dab2a3a5d0785fd0cc155 which uses xchain.io/blocktrail.com for most requets, with failover to blockr.io and chain.so

**Comment by theBliz** [comment]
not sure if connected, but for future references, CMC doesn't allow client-side js calls. Check the doc here https://coinmarketcap.com/api/documentation/v1/#section/Quick-Start-Guide

![Screen Shot 2019-03-16 at 21 58 05](https://user-images.githubusercontent.com/10141807/54482219-3b31d200-4838-11e9-95cb-1421a98cbed3.png)
