### ISSUE TITLE
unable to place a decimal in send amount on iOS

### ISSUE THREAD

**Issue by ShawnLeary** [jdogresorg/FreeWallet#9]
not seeing a decimal/period character "." as an option when typing the amount in the Send box for a Bitcoin send.  latest and greatest iOS  10.3.2

**Comment by ShawnLeary** [comment]
just realized that the decimal appears after you click out of the box.  i wanted to send less 1 so i would have to leave. box and then edit to correct.

**Comment by jdogresorg** [comment]
When a user on a mobile device taps an input field, the app needs to decide what type of keyboard to show.

Since 99.99% of the stuff your going to type is numbers, it makes sense to throw the 'tel' telephone keyboard..... unfortunately, this keyboard does not have the period key. Previously I was throwing the full keyboard, but users were complaining that they just wanted to see the telephone keyboard so they could enter numbers easily. I also tried a hacky method where I would detect the missing period and restore the previous value, but it wound up making the UI act a big wierd.

As you discovered, when you click out of the field, the period is automatically re-inserted back into the number. This was the solution I came up with for how to keep a period in the amount. :)
